post_install(){
rm -f /usr/share/gnome-background-properties/adwaita.xml
rm -f /usr/share/gnome-background-properties/gnome-default.xml
rm -rf /usr/share/backgrounds/xfce
mv /usr/share/backgrounds/swagarch/ /usr/share/backgrounds/xfce
rm -f /usr/share/gnome-background-properties/gnome-backgrounds.xml
cp /usr/share/gnome-background-properties/swagarch-backgrounds.xml /usr/share/gnome-background-properties/gnome-backgrounds.xml
chmod -R 755 /usr/share/backgrounds/xfce
}

post_remove(){
rm -rf /usr/share/backgrounds/swagarch
rm -f /usr/share/gnome-background-properties/swagarch-backgrounds.xml
}

pre_upgrade(){
rm -rf /usr/share/backgrounds/swagarch
rm -f /usr/share/gnome-background-properties/swagarch-backgrounds.xml
}

post_upgrade(){
rm -f /usr/share/gnome-background-properties/adwaita.xml
rm -f /usr/share/gnome-background-properties/gnome-default.xml
rm -rf /usr/share/backgrounds/xfce
mv /usr/share/backgrounds/swagarch/ /usr/share/backgrounds/xfce
rm -f /usr/share/gnome-background-properties/gnome-backgrounds.xml
cp /usr/share/gnome-background-properties/swagarch-backgrounds.xml /usr/share/gnome-background-properties/gnome-backgrounds.xml
}

